'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const {WheelIntent,normalizeWheel,canScroll}=require('../src/scroll.js');
const series=(values,times)=>{const w=new WheelIntent();return values.map((d,i)=>w.read(d,times?.[i]??i*40).step)};
test('four wheel notches retarget four sections in 210ms, no 650ms lock',()=>assert.deepEqual(series([120,120,120,120],[0,70,140,210]),[1,1,1,1]));
test('reverse on the next notch without waiting for landing',()=>assert.deepEqual(series([120,120,-120,-120],[0,60,120,180]),[1,1,-1,-1]));
test('steady trackpad travel advances multiple sections during one stroke',()=>assert.equal(series(Array(20).fill(20)).reduce((a,b)=>a+b,0),4));
test('gentle continued input after a large opening pulse is never strength-gated',()=>assert.equal(series([120,...Array(10).fill(20)]).reduce((a,b)=>a+b,0),3));
test('a fresh 40px notch at the artist panel top returns home',()=>assert.equal(new WheelIntent().read(-40,0,false).step,-1));
test('slow small unconsumed mouse notches accumulate',()=>assert.deepEqual(series([-20,-20],[0,240]),[0,-1]));
test('unfinished input expires after a real pause',()=>assert.deepEqual(series([20,20],[0,700]),[0,0]));
test('tiny residual input is not amplified into another section',()=>assert.equal(series([120,...Array(12).fill(.5)]).reduce((a,b)=>a+b,0),1));
test('a stronger long trackpad flick may intentionally pass multiple sections',()=>assert.ok(series(Array.from({length:24},(_,i)=>120*.91**i)).reduce((a,b)=>a+b,0)>1));
test('no input causes no delayed navigation replay',()=>{const w=new WheelIntent();w.read(120,0);assert.deepEqual(w.read(0,5000),{prevent:false,step:0});assert.equal(w.sum,0)});
test('a single huge wheel event is bounded to one target change',()=>assert.equal(new WheelIntent().read(9000,0).step,1));
test('direction changes clear accumulated forward distance',()=>{const w=new WheelIntent();w.read(120,0);w.read(80,40);assert.equal(w.read(-40,70).step,-1);assert.equal(w.sum,0)});
test('alternating tiny reverse noise does not switch sections',()=>assert.deepEqual(series([120,-2,2,-2,2]),[1,0,0,0,0]));
test('gentle deliberate reverse accumulates without a timer',()=>assert.deepEqual(series([120,-12,-12,-12]),[1,0,0,-1]));
test('readable panel retains native scrolling',()=>assert.deepEqual(new WheelIntent().read(120,0,true),{prevent:false,step:0}));
test('panel reading does not leak into navigation at its bottom',()=>{const w=new WheelIntent();w.read(120,0,true);assert.deepEqual(w.read(100,50,false),{prevent:true,step:0})});
test('a fresh outward stroke at the panel boundary advances',()=>{const w=new WheelIntent();w.read(120,0,true);assert.equal(w.read(40,250,false).step,1)});
test('newly visible panel does not steal ongoing scene navigation',()=>{const w=new WheelIntent();w.read(120,0,false);assert.deepEqual(w.read(120,70,true),{prevent:true,step:1})});
test('native reading can reverse while it still has room',()=>{const w=new WheelIntent();w.read(120,0,true);assert.deepEqual(w.read(-10,40,true),{prevent:false,step:0})});
test('click/visibility reset forgets earlier gesture ownership',()=>{const w=new WheelIntent();w.read(120,0,false);w.reset();assert.deepEqual(w.read(10,40,true),{prevent:false,step:0})});
test('pixel, line and page delta units normalize',()=>{assert.deepEqual(normalizeWheel({deltaX:1,deltaY:-3,deltaMode:1}),{x:16,y:-48});assert.equal(normalizeWheel({deltaX:0,deltaY:1,deltaMode:2},900).y,900)});
test('three-line wheel movement is enough for the first step',()=>assert.equal(new WheelIntent().read(normalizeWheel({deltaX:0,deltaY:3,deltaMode:1}).y,0).step,1));
test('panel native scrolling checks the actual directional boundary',()=>{const e={scrollTop:50,scrollHeight:500,clientHeight:200};assert.equal(canScroll(e,-1),true);assert.equal(canScroll(e,1),true);e.scrollTop=0;assert.equal(canScroll(e,-1),false);e.scrollTop=300;assert.equal(canScroll(e,1),false)});
test('fractional/negative overscroll and nonoverflow content are bounded',()=>{assert.equal(canScroll({scrollTop:-.5,scrollHeight:500,clientHeight:200},-1),false);assert.equal(canScroll({scrollTop:0,scrollHeight:200,clientHeight:200},1),false)});
test('bad values cannot corrupt intent',()=>{const w=new WheelIntent();for(const d of [NaN,Infinity,-Infinity,0,.1])assert.equal(w.read(d,0).step,0);assert.equal(w.read(40,NaN).step,0);assert.equal(w.read(40,10).step,1)});
test('replayed capture times give identical input decisions despite delivery delays',()=>{const values=[120,120,20,20,20,20,20,-40];const times=values.map((_,i)=>i*45);assert.deepEqual(series(values,times),[1,1,0,0,0,0,1,-1])});
